FROM ubuntu:20.04
MAINTAINER Pascal Quach <pascal.quach.utc@gmail.com>

ENV DEBIAN_FRONTEND noninteractive
ENV PLANTUML_JAR=/usr/bin/plantuml

# Install.
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y \
texlive \
texlive-latex-recommended \
texlive-latex-extra \
texlive-luatex \
texlive-lang-all \
plantuml \
inkscape
