FROM ubuntu:20.04
MAINTAINER Pascal Quach <pascal.quach.utc@gmail.com>

ENV DEBIAN_FRONTEND noninteractive
ENV PLANTUML_JAR=/usr/local/bin/plantuml/plantuml.jar

# Install.
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y \
texlive \
texlive-latex-recommended \
texlive-latex-extra \
texlive-luatex
